# user_campaign_filtering/docker-compose.yml

version: '2'
services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: user_campaign_filtering_development
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3307:3306"
    app:
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
            - ".:/user_campaign_filtering"
        ports:
            - "3000:3000"
        depends_on:
            - db
        links:
            - db
        environment:
            DB_USER: root
            DB_NAME: user_campaign_filtering_development
            DB_PASSWORD: password
            DB_HOST: db